include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 80

analyzer:
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: error
    # allow having TODOs in the code
    todo: ignore
  exclude:
    - 'bin/cache/**'
    # see https://github.com/dart-lang/sdk/issues/28463
    - '**/i18n/string_messages_**.dart'
    - '/**/i18n/string_messages_**.dart'
    - '**/i18n/string_messages_***.dart'
    - '/**/i18n/string_messages_***.dart'
    - 'lib/src/http/**'

linter:
  rules:
    camel_case_types: false
    library_names: false
    library_prefixes: false
    package_names: false
    file_names: false
    avoid_print: false
    camel_case_extensions: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    unintended_html_in_doc_comment: false
    use_key_in_widget_constructors: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_library_prefixes: false
    prefer_interpolation_to_compose_strings: false
    prefer_const_constructors_in_immutables: false
    curly_braces_in_flow_control_structures: false
    prefer_function_declarations_over_variables: false
    no_leading_underscores_for_local_identifiers: false
