name: celest_backend
description: The Celest backend for mobile_app_flutter_celest.
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  celest: ^0.2.0
  celest_core: ^0.2.1
  http: ">=0.13.0 <2.0.0"
  fast_immutable_collections: ^10.1.0
  i18n_extension_core: ^2.0.6
  meta: ^1.10.0
  collection: ^1.17.2
  intl: 0.18.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
celest:
  project:
    id: 018d8ffe-108e-73d6-a735-f6d9f30fc0b2
