// Generated by Celest. This file should not be modified manually, but
// it can be checked into version control.
// ignore_for_file: type=lint, unused_local_variable, unnecessary_cast, unnecessary_import

library;

import 'package:celest/celest.dart';

abstract final class apis {
  static const database = CloudApi(name: r'database');

  static const portfolio = CloudApi(name: r'portfolio');

  static const stocks = CloudApi(name: r'stocks');
}

abstract final class functions {
  static const databaseInit = CloudFunction(
    api: r'database',
    functionName: r'init',
  );

  static const portfolioAddCashBalance = CloudFunction(
    api: r'portfolio',
    functionName: r'addCashBalance',
  );

  static const portfolioBuyStock = CloudFunction(
    api: r'portfolio',
    functionName: r'buyStock',
  );

  static const portfolioRemoveCashBalance = CloudFunction(
    api: r'portfolio',
    functionName: r'removeCashBalance',
  );

  static const portfolioSellStock = CloudFunction(
    api: r'portfolio',
    functionName: r'sellStock',
  );

  static const stocksReadAvailableStocks = CloudFunction(
    api: r'stocks',
    functionName: r'readAvailableStocks',
  );

  static const stocksReadUpdatedStockPrice = CloudFunction(
    api: r'stocks',
    functionName: r'readUpdatedStockPrice',
  );
}
