name: mobile_app_flutter_celest
description: Mobile App Example using Celest
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  celest_core: ^0.1.0
  celest_backend:
    path: celest/
  async_redux: ^21.4.0
  align_positioned: ^4.0.0
  animated_size_and_fade: ^4.0.0
  animations: ^2.0.11
  bdd_framework: ^3.0.1
  assorted_layout_widgets: ^9.0.0
  characters: ^1.3.0
  collection: ^1.17.2
  connectivity: ^3.0.6
  crypto: ^3.0.3
  fast_immutable_collections: ^10.1.0
  flutter_svg: ^2.0.9
  http: ^1.1.2
  i18n_extension: ^10.0.1
  intl: 0.18.1
  matrix4_transform: ^3.0.0
  themed: ^5.0.0
  timezone: ^0.9.2
  weak_map: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
